export const vetCenters = [
  {
    name: "Centro Veterinario Triana",
    phone: "+34 955 911 305",
    location: "Sevilla",
    city: "Sevilla",
    distance: 10,
  },
  {
    name: "Centro Veterinario Los Remedios",
    phone: "+34 955 912 306",
    location: "Sevilla",
    city: "Sevilla",
    distance: 12,
  },
  {
    name: "Centro Veterinario Nervión",
    phone: "+34 955 913 307",
    location: "Sevilla",
    city: "Sevilla",
    distance: 15,
  },
  {
    name: "Centro Veterinario Alameda",
    phone: "+34 955 914 308",
    location: "Sevilla",
    city: "Sevilla",
    distance: 18,
  },
  {
    name: "Centro Veterinario San Bernardo",
    phone: "+34 955 915 309",
    location: "Córdoba",
    city: "Córdoba",
    distance: 140,
  },
  {
    name: "Centro Veterinario Arenal",
    phone: "+34 955 916 310",
    location: "Granada",
    city: "Granada",
    distance: 250,
  },
  {
    name: "Centro Veterinario Tetuán",
    phone: "+34 955 917 311",
    location: "Málaga",
    city: "Málaga",
    distance: 210,
  },
  {
    name: "Centro Veterinario El Porvenir",
    phone: "+34 955 918 312",
    location: "Huelva",
    city: "Huelva",
    distance: 100,
  },
  {
    name: "Centro Veterinario San Lorenzo",
    phone: "+34 955 919 313",
    location: "Cadiz",
    city: "Cadiz",
    distance: 120,
  },
  {
    name: "Centro Veterinario Macarena",
    phone: "+34 955 920 314",
    location: "Almería",
    city: "Almería",
    distance: 300,
  },
  {
    name: "Centro Veterinario Ronda",
    phone: "+34 955 921 315",
    location: "Jaén",
    city: "Jaén",
    distance: 180,
  },
  {
    name: "Centro Veterinario Reina Mercedes",
    phone: "+34 955 922 316",
    location: "Sevilla",
    city: "Sevilla",
    distance: 5,
  },
  {
    name: "Centro Veterinario Santa Justa",
    phone: "+34 955 923 317",
    location: "Sevilla",
    city: "Sevilla",
    distance: 8,
  },
  {
    name: "Centro Veterinario Mairena",
    phone: "+34 955 924 318",
    location: "Mairena del Aljarafe",
    city: "Sevilla",
    distance: 15,
  },
  {
    name: "Centro Veterinario Dos Hermanas",
    phone: "+34 955 925 319",
    location: "Dos Hermanas",
    city: "Sevilla",
    distance: 10,
  },
  {
    name: "Centro Veterinario Tomares",
    phone: "+34 955 926 320",
    location: "Tomares",
    city: "Sevilla",
    distance: 7,
  },
  {
    name: "Centro Veterinario Camas",
    phone: "+34 955 927 321",
    location: "Camas",
    city: "Sevilla",
    distance: 6,
  },
  {
    name: "Centro Veterinario San Juan",
    phone: "+34 955 928 322",
    location: "San Juan de Aznalfarache",
    city: "Sevilla",
    distance: 5,
  },
  {
    name: "Centro Veterinario Gelves",
    phone: "+34 955 929 323",
    location: "Gelves",
    city: "Sevilla",
    distance: 4,
  },
  {
    name: "Centro Veterinario La Algaba",
    phone: "+34 955 930 324",
    location: "La Algaba",
    city: "Sevilla",
    distance: 8,
  },
];